spring:
  datasource:
    url: jdbc:h2:mem:user
    username: root
    password: sa
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

